### ISSUE TITLE
Does it Matter If I Use a TN-Type Module?

### ISSUE THREAD

**Issue by AlexLandherr** [gavinlyonsrepo/HD44780_LCD_RPI#2]
I found this TN-type HD44780 compatible controller:
[https://www.electrokit.com/produkt/lcd-2x16-tecken-tn-led/](https://www.electrokit.com/produkt/lcd-2x16-tecken-tn-led/)

Is it of any importance that it is of a TN-type instead of STN?

The description of the above module says TN-type displays have a higher refresh rate.

EDIT: Also found the right backpack controller here:
[https://www.electrokit.com/produkt/i2c-interface-for-lcd/](https://www.electrokit.com/produkt/i2c-interface-for-lcd/)

**Comment by gavinlyonsrepo** [comment]
No.

> Is it of any importance that it is of a TN-type instead of STN?

No.
